2025-10-18 09:31:18,829 : INFO : root : Loading config.
2025-10-18 09:31:18,832 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-10-18 09:31:18,833 : INFO : ConfigProcessor : Loading config from cache: C:\Users\antho\AppData\Local\Temp\fdca14d0c9d658ab8200d57120800af5.mpf_cache
2025-10-18 09:31:18,947 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\antho\nightpin\modes\attract\config\attract.yaml
2025-10-18 09:31:18,948 : INFO : ConfigProcessor : Loading config from file C:\Users\antho\mpf\Lib\site-packages\mpf\modes\attract\config\attract.yaml.
2025-10-18 09:31:18,949 : INFO : ConfigProcessor : Loading config: C:\Users\antho\mpf\Lib\site-packages\mpf\modes\attract\config\attract.yaml
2025-10-18 09:31:18,949 : INFO : ConfigProcessor : Loading config from file C:\Users\antho\nightpin\modes\attract\config\attract.yaml.
2025-10-18 09:31:18,960 : INFO : ConfigProcessor : Loading config: C:\Users\antho\nightpin\modes\attract\config\attract.yaml
2025-10-18 09:31:18,961 : INFO : ConfigProcessor : Config file cache created: C:\Users\antho\AppData\Local\Temp\5dec96b1547c4adf5bdd3d1715e74bc0.mpf_cache
2025-10-18 09:31:18,961 : INFO : ConfigProcessor : Loading config from cache: C:\Users\antho\AppData\Local\Temp\202a5840610e95051f9f473dfa660cc0.mpf_cache
2025-10-18 09:31:18,962 : INFO : ConfigProcessor : Loading config from cache: C:\Users\antho\AppData\Local\Temp\5dec96b1547c4adf5bdd3d1715e74bc0.mpf_cache
2025-10-18 09:31:18,973 : INFO : ConfigProcessor : Loading config from cache: C:\Users\antho\AppData\Local\Temp\2cd13a2d3f375e00ab01d6d09a85d8e7.mpf_cache
2025-10-18 09:31:18,974 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev11
2025-10-18 09:31:18,974 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2025-10-18-09-31-18-mpf-LAPTOP-MPGP6R69.log', 'pause': False, 'production': False, 'text_ui': False, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'full_logfile_path': 'C:\\Users\\antho\\nightpin\\logs\\2025-10-18-09-31-18-mpf-LAPTOP-MPGP6R69.log'}
2025-10-18 09:31:18,974 : INFO : Machine : MPF path: C:\Users\antho\mpf\Lib\site-packages\mpf
2025-10-18 09:31:18,974 : INFO : Machine : Machine path: C:\Users\antho\nightpin
2025-10-18 09:31:18,974 : INFO : Machine : Platform: win32
2025-10-18 09:31:18,974 : INFO : Machine : Python executable location: C:\Users\antho\mpf\Scripts\python.exe
2025-10-18 09:31:18,974 : INFO : Machine : Python version: 3.12.7 (64-bit)
2025-10-18 09:31:18,976 : INFO : Machine : Initializing MPF...
2025-10-18 09:31:19,073 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-10-18 09:31:19,100 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-10-18 09:31:19,100 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev11', 'prev_value': None, 'change': True}
2025-10-18 09:31:19,100 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev11, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-10-18 09:31:19,100 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.12.7', 'prev_value': None, 'change': True}
2025-10-18 09:31:19,259 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-11-10.0.26100-SP0', 'prev_value': None, 'change': True}
2025-10-18 09:31:19,259 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-10-18 09:31:19,259 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '11', 'prev_value': None, 'change': True}
2025-10-18 09:31:19,259 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.26100', 'prev_value': None, 'change': True}
2025-10-18 09:31:19,259 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-10-18 09:31:19,259 : INFO : EventManager : Event: ======'machine_var_log_file_path'====== Args={'value': 'C:\\Users\\antho\\nightpin\\logs\\2025-10-18-09-31-18-mpf-LAPTOP-MPGP6R69.log', 'prev_value': None, 'change': True}
2025-10-18 09:31:19,259 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-10-18 09:31:19,284 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2025-10-18 09:31:19,285 : INFO : ball_device.bd_trough : BCH: Initial count: 0
2025-10-18 09:31:19,285 : INFO : ball_device.bd_trough : State: idle
2025-10-18 09:31:19,296 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2025-10-18 09:31:19,297 : INFO : EventManager : Event: ======'init_phase_4'====== Args={}
2025-10-18 09:31:19,297 : INFO : BallController : Initial balls found: 0
2025-10-18 09:31:19,298 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe...kill_lanes>')>)
handle: <Handle EventManager._queue_task_done(<Task finishe...kill_lanes>')>)>
Traceback (most recent call last):
  File "C:\Users\antho\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\events.py", line 795, in _queue_task_done
    future.result()
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\devices\switch.py", line 81, in _check_duplicate_switch_numbers
    raise AssertionError(
AssertionError: Duplicate switch number 4 for switch <switch.s_outer_skill_lanes>
2025-10-18 09:31:19,316 : INFO : Machine : Starting the main run loop with active modes: []
2025-10-18 09:31:19,317 : WARNING : Machine : Attract mode is not active, game will not be playable. Please check your attract mode configuration.
2025-10-18 09:31:19,317 : INFO : Machine : Shutting down...
2025-10-18 09:31:19,317 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-10-18 09:31:20,333 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\machine.py", line 810, in _run_loop
    raise self._exception['exception']
  File "C:\Users\antho\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\events.py", line 795, in _queue_task_done
    future.result()
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\core\events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\antho\mpf\Lib\site-packages\mpf\devices\switch.py", line 81, in _check_duplicate_switch_numbers
    raise AssertionError(
AssertionError: Duplicate switch number 4 for switch <switch.s_outer_skill_lanes>
2025-10-18 09:31:20,335 : INFO : root : MPF run loop ended.
